### ISSUE TITLE
CI is unhappy across the board

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#116]
I am on the move ATM, @jwodder please check it out

**Comment by yarikoptic** [comment]
indeed, thanks! Please submit PRs fixing those extensions still seeking `datalad.tests.utils`, or issues asking for a release if the y have changes not released.

`datalad_osf` - I guess also just needs release since https://github.com/datalad/datalad-osf/issues/165 was fixed recently.  Filed https://github.com/datalad/datalad-osf/issues/179 .

Please look into that genuine datalad_container issue

**Comment by yarikoptic** [comment]
pushed "fix" 42043834c64f34a78cf5cad2dfc68997b7261e72 and regenerated for osf and neuroimaging -- they are already not using nose which we specify here in the spec.

**Comment by jwodder** [comment]
@yarikoptic Is datalad-xnat dead?  There have been no serious commits since 2021, and the GitHub Actions workflow still uses Python 3.6.

**Comment by jwodder** [comment]
@yarikoptic PRs:

* https://github.com/mih/datalad-mihextras/pull/38
* https://github.com/datalad/datalad-xnat/pull/148
* https://github.com/datalad/datalad-catalog/pull/320

**Comment by yarikoptic** [comment]
> @yarikoptic Is datalad-xnat dead? There have been no serious commits since 2021, and the GitHub Actions workflow still uses Python 3.6.

according to @mih it is used, just not actively developed.  If you could send face lift of switching to 3.8 and any other minimal changes needed - would be appreciated.

**Comment by jwodder** [comment]
I was unable to figure out why the `datalad-container` tests were failing (It seemed like `docker save` was creating `manifest.json` files that didn't follow the structure the code expected), but they've since stopped failing on their own.

**Comment by yarikoptic** [comment]
Thank you for looking into it @jwodder . datalad-container is all green now indeed, which is great. Hopefully docker stays more consistent from now on.

**Comment by yarikoptic** [comment]
I don't think we have it "Across the board" ATM indeed.
