### ISSUE TITLE
incorrect badge

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#125]
for metalad I keep getting email notifications about failures and indeed https://github.com/datalad/datalad-extensions/actions?query=workflow%3Atest-datalad_metalad-maint is full of red 

but the badge is green for both of the runs:

[![Released+DataLad master](https://github.com/datalad/datalad-extensions/workflows/test-datalad_metalad-master/badge.svg)](https://github.com/datalad/datalad-extensions/actions?query=workflow%3Atest-datalad_metalad-master) | [![Released+DataLad maint](https://github.com/datalad/datalad-extensions/workflows/test-datalad_metalad-maint/badge.svg)](https://github.com/datalad/datalad-extensions/actions?query=workflow%3Atest-datalad_metalad-maint) 

I do not see where could be the catch besides some bug on github side.  @jwodder -- WDYT?

**Comment by jwodder** [comment]
@yarikoptic I don't know why the badges are like that, but it'd probably be a good idea to update the badge URLs, as GitHub changed the URL format some months ago.

* Before: `https://github.com/{repo_owner}/{repo_name}/workflows/{workflow_display_name}/badge.svg`
* After: `https://github.com/{repo_owner}/{repo_name}/actions/workflows/{workflow_filename}/badge.svg`

So https://github.com/datalad/datalad-extensions/workflows/test-datalad_metalad-maint/badge.svg would become https://github.com/datalad/datalad-extensions/actions/workflows/test-datalad_metalad-maint.yaml/badge.svg, which is currently red.
