### ISSUE TITLE
Build (test) git-annex on Windows in github actions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#37]
https://git-annex.branchable.com/install/Windows/ provides some instructions on HOWTO.  If they aren't sufficient - we will dig deeper, e.g. ask @joeyh and may be Yuri who established Jenkins setup in qemu on one of the servers in the dungeons, but it is a black box to me.

Note:
- ATM windows builds come without libmagic/file support.  So enabling that one could be postponed until basic build setup is functioning. Some pointers etc from my attempts could be found at [git-annex website comment](https://git-annex.branchable.com/todo/provide_windows_build_with_MagicMime/#comment-36e31d0ae3d55820482ce7e35badd70c)

probably should be a separate workflow to start with, and not sure if it would be feasible to meld it into the one we have for linux + OSX now.

**Comment by jwodder** [comment]
Building git-annex on Windows currently fails with a type error: https://git-annex.branchable.com/bugs/Build_fails_with_type_error_on_Windows

**Comment by yarikoptic** [comment]
thanks for reporting -- joey reported have fixed it... feels like he might like to get Windows CI running too ;)
