### ISSUE TITLE
add testing of datalad for windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#49]
not all tests are "windows friendly" yet but we have a good number of them running in datalad via appveyor.  We should replicate (and may be eventually extend) that list of them here while testing upon successful build of datalad.

**Comment by jwodder** [comment]
@yarikoptic So you want a new GitHub Actions workflow in this repo that reproduces [this appveyor config](https://github.com/datalad/datalad/blob/master/appveyor.yml)?

**Comment by jwodder** [comment]
@yarikoptic @mih What is the `tools\ci\appveyor_ssh_config` file mentioned [here](https://github.com/datalad/datalad/blob/7d31c354ea7c764ef8817aea71ff70c1e157b1b5/appveyor.yml#L47)?  I can't find any documentation on it.
