### ISSUE TITLE
please publish build-version artifact for windows build

### ISSUE THREAD

**Issue by joeyh** [datalad/datalad-extensions#55]
The windows build workflow builds this file, but never does anything with it:

    ./Build/BuildVersion > dist/build-version

Could you please publish this file as an artifact, so that it ends up at eg
http://datasets.datalad.org/datalad/packages/windows/git-annex-installer_latest-snapshot_x64.build-version or something like that. (Any stable url will do.)

This file is used to determine what exact version of git-annex a build is, which gets used when git-annex is upgrading itself from an older build. Currently working out what exact version http://datasets.datalad.org/datalad/packages/windows/git-annex-installer_latest-snapshot_x64.exe is a build of is difficult.

**Comment by yarikoptic** [comment]
yeap, roger that.
@jwodder could you please adjust the workflow to produce/upload this file as part of the git-annex-installer.zip "bundle"?
