### ISSUE TITLE
Move git-annex workflows to https://github.com/datalad/git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#67]
To facilitate testing etc of git-annex, and testing of possible changes/fixes to git-annex to prepare patches to be sent to @joeyh, we better move out all of its workflows into a separate repo with the full git-annex codebase.  I did not dare to establish github.com/git-annex, so initiated https://github.com/datalad/git-annex .

We would still like to have banners in README to point to their health status here (similarly to how we do it for datalad).

**Comment by jwodder** [comment]
@yarikoptic To be clear: You want `.github/workflows/build-git-annex-*.yml` to be moved in their entirety to this new repo, and the banners in the README in datalad-extensions should be updated to refer to the actions in the new repo.  Is that what you're asking?

**Comment by yarikoptic** [comment]
Yes. Also workflows adjusted to not clone git annex since it will be that repository providing it, but now I realized that we then would need to maintain our own master branch merging workflows in, that is suboptimal :-/  may be we keep master as git annex original has it, and use main as our branch with added workflows etc. But ideally we need to build from master it at least adjust git describe call to operate on the merge base between that main and master to get correct annex version

**Comment by jwodder** [comment]
@yarikoptic So should I create a PR against master or against a new "main" branch?  Is main going to contain anything other than workflows, i.e., will it need to be updated alongside master?  Also, I think scheduled workflows only run when they're on the default branch, so main might have to become the default branch.  There are also going to be problems if the official repo ever renames its master to main.

**Comment by jwodder** [comment]
@yarikoptic Also, how should files from this repository that are needed for the workflows — like `scripts/ci/build_git_annex` — be handled?  Normally, I would move them to the new repository, but if the workflows are going to be on a separate branch from the code, that would get messy.  Should they just continue to live in datalad-extensions?

**Comment by jwodder** [comment]
@yarikoptic Note that the `datalad_builder_gpgkey` secret will need to be added to the new repository in order for the Linux build to work.

**Comment by yarikoptic** [comment]
branch/scripts:  
- if official `git-annex` switches to main, we could always adjust to account. But may be we should just place all "original" branches under `original/` namespace "folder".  It would make it clean(er).  PRs to test patches to git-annex code would need to be submitted (but never merged) against `main`, and we nohow touch `original/` branches (if multiple, `master` only for now)

NB may be you have better naming ideas over `original/`?

scripts - yes, move them here. I see two possibilities (there could be more)
  - As part of the cron job we could merge `original/master` into this `master` (or `main`, whatever -- you decide and feel welcome to change - doesn't matter to me, "main" might be better since it is not `master` as `original/master` would be).  It will be lots of avoidable merge commits, but would establish clean history/dependency between what was the state we were testing etc. 
  - We could just `git read-tree` from `original/master` during build and thus keep only our scripts etc.  but that would preclude testing of patches to git-annex AFAIK - a feature I want us to have for the long(er) run.  So, I guess we should just proceed with above and having those merges into `main`.

**Comment by yarikoptic** [comment]
NB. I was trying to stay away from `upstream/` but I think it is actually the best term to use here (instead of `original/`)

**Comment by yarikoptic** [comment]
they were moved!
