### ISSUE TITLE
install git-annex not from here but from datalad/git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#69]
ATM all extensions fail to test (only since a day ago somehow - probably artifacts finally expired)

We need to have 
```
          datalad-extensions-latest)
            sudo eatmydata apt-get install jq
            GITHUB_TOKEN=${{ secrets.datalad_github_token }} ./scripts/ci/download-latest-artifact
            sudo eatmydata dpkg -i download/*.deb

```
in the template adjusted to 
- rename to `datalad-git-annex-latest`
- install from artifacts of `https://github.com/datalad/git-annex/` 

might be worth to remove that `download-latest-artifact` and just keep a copy of the datalad/install.py from the datalad repository which should accomplish that as well.

**Comment by jwodder** [comment]
The script in this repository already installs from `datalad/git-annex`; I believe it's failing because (unlike the version in `datalad/datalad`) it doesn't filter out failed workflow runs.
