### ISSUE TITLE
failing to fetch git-annex build from datalad/git-annex: bad credentials

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#72]
```
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.
Using curl as "curl --silent"
Getting artifacts_url from https://api.github.com/repos/datalad/git-annex/actions/workflows/build-ubuntu.yaml/runs?status=success&branch=master into /tmp/tmp.uomamAtfxT
Unable to get artifacts_url
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
Error: Process completed with exit code 1.
```
see e.g.  https://github.com/datalad/datalad-extensions/runs/1571587991?check_suite_focus=true

@jwodder - do you have an immediate idea on what is wrong?

**Comment by jwodder** [comment]
@yarikoptic If you haven't messed with any permissions lately, my current guess is that it might be more auth flakiness on GitHub's end, like whatever was causing https://github.com/datalad/git-annex/issues/32.

**Comment by yarikoptic** [comment]
I think I was not messing with anything related recently, but some times I loose track quite quickly on some "quick changes" while doing a number of things in parallel.  Need some kind of a conceptual mental `git log` ;)  It seems to be quite consistent in failing to be just flakiness, but ok - let's wait a bit more and then I will try to dig out the issue.

**Comment by yarikoptic** [comment]
Started to fail again in some runs although differently

```
Using curl as "curl --silent"
Getting artifacts_url from https://api.github.com/repos/datalad/git-annex/actions/workflows/build-ubuntu.yaml/runs?status=success&branch=master into /tmp/tmp.PDV19oN237
Getting archive download url from https://api.github.com/repos/datalad/git-annex/actions/runs/467805073/artifacts
Getting download url from https://api.github.com/repos/datalad/git-annex/actions/artifacts/34085739/zip
Error: Process completed with exit code
```
I guess I will remove silent option to see what is going on. May be just need to spread runs apart in time
