### ISSUE TITLE
Add datalad-htcondor

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#86]
https://github.com/datalad/datalad-htcondor
has tests, but apparently not tested here

Attn @mih if you get a moment

**Comment by mih** [comment]
This extension has not seen a single commit in 3 years. I don't think it is worth burning coal for it.

**Comment by yarikoptic** [comment]
I am not discriminating for Age etc, just given that it would also be promoted as a replacement for pbs option in https://github.com/datalad/datalad/pull/5956, do not test against it in datalad core, and not sure if datalad-htcondor tests itself on cron -- I think adding testing here to ensure that it is not yet broken would be of benefit..

Eventually -- I hope we would also add testing against bleeding edge builds of git-annex which would then benefit even more.

**Comment by mih** [comment]
It is not promoted as a replacement!

**Comment by mih** [comment]
This project will be cleaned up. It should not be tested here.
