### ISSUE TITLE
establish con/tinuous setup for this repo as well

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#88]
to go along side with others on `datalad@smaug` just to fetch CI build logs.

I guess configuration could be similar to the one for datalad. IMHO no need for annexing logs within each month.

Historically -- go back just as much as reasonable / have access to (month?)

**Comment by jwodder** [comment]
@yarikoptic FYI, I noticed while setting up tinuous that scheduled builds stopped around the 28th because of a lack of activity in the repository.  You need to select each deactivated workflow on the "Actions" page and click "Enable workflow" to re-enable them.  If & when the repository goes another 60 days without commit activity, you (or *someone*) should get an e-mail a few days before notifying you that the workflows are about to be disabled.

**Comment by jwodder** [comment]
@yarikoptic tinuous is now set up for this repository at `smaug:/mnt/datasets/datalad/ci/datalad-extensions`.

**Comment by yarikoptic** [comment]
Awesome, thank you @jwodder !

**Comment by yarikoptic** [comment]
> @yarikoptic FYI, I noticed while setting up tinuous that scheduled builds stopped around the 28th because of a lack of activity in the repository. You need to select each deactivated workflow on the "Actions" page and click "Enable workflow" to re-enable them. If & when the repository goes another 60 days without commit activity, you (or _someone_) should get an e-mail a few days before notifying you that the workflows are about to be disabled.

Thank you for the this note! Didn't know about this. I guess it might be an issue at some point for some other cron based action setups (eg git annex). Need to keep an eye on it. I will reopen this one so I don't forget to fix that tomorrow

**Comment by yarikoptic** [comment]
Might be even crafting some drop in action to check daily and if no recent (50 days?) commits, push a dummy empty commit?

**Comment by yarikoptic** [comment]
FTR - reenabled one workflow and then pushed an empty commit to cause 'activity'.  Will check tomorrow if all the rest of workflows would get auto-reenabled by tomorrow.

**Comment by yarikoptic** [comment]
added/ran the script in 637c61fa8e4935aa1c7a90469017c110b5e6ffb1 -- all reenabled now
