### ISSUE TITLE
Add a workflow which would keep the repo "active"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#89]
As mentioned by @jwodder (thanks again) -- we need to keep the repository "active" so we don't need to go through manual reenabling all individual actions (it is a pain todo manually, probably will try to program it up to enable all).

Looking forward, I think we should ensure that actions are not disabled.  A crude way would be to push a new empty commit, or may be an activity on some placeholder issue would suffice?

**Comment by jwodder** [comment]
@yarikoptic [The heartbeat workflow is still running](https://github.com/datalad/datalad-extensions/actions/workflows/heartbeat.yaml); what makes you think anything got stale?

**Comment by yarikoptic** [comment]
Doh, I guess I got confused by a memory that I saw datalad/git-annex repo having large distance between recent CI runs, and the fact that this issue is still open. Let's close it
